name = "DiscoverEpidemicModel"
uuid = "3fd60281-8f7d-4d5c-81b1-0114bc713a7d"
authors = ["Morteza Babazadeh", "Rainer Heintzmann", "René Lachmann"]
version = "0.0.1"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
